# Generated by Django 4.0.2 on 2022-02-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Found it', max_length=255),
        ),
    ]
