# Generated by Django 4.0.2 on 2022-02-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
