# Generated by Django 4.0.2 on 2022-02-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
